---
# User configuration.
github_username: ["johnny-hausman", "roguisharcanetrickster", "elephanteleven", "joshAppDev"]

# Location where configuration files will be stored.
config_dir: '/scry-pi'

# Domain names configuration (related services need to be enabled).
domain_name_enable: false

# Pi-hole configuration.
pihole_enable: false

# Internet monitoring configuration.
monitoring_enable: true
monitoring_speedtest_interval: 60m
monitoring_ping_interval: 5s
monitoring_ping_hosts:  # [URL];[HUMAN_READABLE_NAME]
  - http://www.google.com/;google.com
  - https://github.com/;github.com
  - https://www.apple.com/;apple.com
  - https://netsuite.cru.org/;netsuite.cru.org
  - https://netsuite.cru.org/;netsuite.cru.org
  - https://cru.org/;cru.org
  - https://okta.com/;okta.com

# Prometheus configuration.
prometheus_monitor_prometheus: false
prometheus_node_exporter_targets:
  - 'nodeexp:9100'
prometheus_extra_scrape_configs: ''
prometheus_tsdb_retention_time: 7d

# Custom Metrics configuration (Also requires `monitoring_enable`)
custom_metrics_enable: true 
custom_metrics_prometheus_url: "http://prometheus:9090"
custom_metrics_location: "" 
custom_metrics_site_id: "" 

