---
- name: Get all running containers
  community.docker.docker_container_info:
    name: "{{ item }}"
  loop:
    - internet-monitoring-custom-metrics-1
    - internet-monitoring-prometheus-1
    - internet-monitoring-ping-1
    - internet-monitoring-speedtest-1
  register: container_info

- name: Fail if any container is not healthy or not running
  ansible.builtin.fail:
    msg: "Container {{ item.invocation.module_args.name }} is not healthy or not running!"
  when: >
    (item.container is not defined) or
    (item.container.State.Status != 'running') or
    (item.invocation.module_args.name == 'internet-monitoring-speedtest-1' and
     item.container.State.Health is defined and
     item.container.State.Health.Status not in ['healthy', 'starting']) or
    (item.invocation.module_args.name != 'internet-monitoring-speedtest-1' and
     item.container.State.Health is defined and
     item.container.State.Health.Status != 'healthy')
  loop: "{{ container_info.results }}"
