---
# TODO: Add credential json to the environment
- name: Create custom-metrics directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ config_dir }}/custom-metrics"
    - "{{ config_dir }}/custom-metrics/config"

- name: Ensure credentials file exists
  ansible.builtin.stat:
    path: "{{ custom_metrics_credentials_path }}"
  register: credentials_file

- name: Fail if credentials file is missing
  ansible.builtin.fail:
    msg: "Google Cloud credentials file not found at {{ custom_metrics_credentials_path }}. Please create a service account and download the credentials JSON file."
  when: not credentials_file.stat.exists

- name: Copy credentials file to custom-metrics config directory
  ansible.builtin.copy:
    src: "{{ custom_metrics_credentials_path }}"
    dest: "{{ config_dir }}/custom-metrics/config/credentials.json"
    mode: '0600'
    remote_src: true

