name: Deploy to Raspberry Pi
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Setup env

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        
      - name: Create new env and activate it
        run: |
          cp example.inventory.ini inventory.ini
          cp example.config.yml config.yml
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      # restart docker
      - name: down 
        run: docker compose down
      - name: up 
        run: docker compose up -d
