name: Tests

on:
  push:
    branches:
      - master
      - pull_updates
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Make test script executable
        run: chmod +x tests/test_update.sh

      - name: Run basic tests
        run: tests/test_update.sh

      - name: Make installer executable
        run: chmod +x setup-pi.sh

      - name: Run installer script
        run: sudo bash ./setup-pi.sh

      - name: Check Ansible installation
        run: ansible --version

      - name: Check Docker installation
        run: docker --version

      - name: Check updater service
        run: systemctl status internet-pi-updater.service || true