name: Tests

on:
  push:
    branches:
      - master
      - pull_updates
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Make test script executable
        run: chmod +x tests/test_update.sh

      - name: Run basic tests
        run: tests/test_update.sh

      - name: Set up Docker repository
        run: |
          # Add Docker's official GPG key:
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          sudo chmod a+r /etc/apt/keyrings/docker.gpg

          # Add the repository to Apt sources:
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update

      - name: Add Turso login data
        run: |
          sudo ./config.sh login < <(printf "libsql://test.turso.io\ntest-auth-token\ntest-location\n1h\n1444\nspeed,ping\ny\n")

      - name: Run installer script
        run: sudo -E bash ./config.sh install

      - name: Check Ansible installation
        run: ansible --version

      - name: Check Docker installation
        run: docker --version

      - name: Check updater service and timer
        run: |
          systemctl status internet-pi-updater.service || true
          systemctl status internet-pi-updater.timer || true

      - name: Check install succeeds after login
        run: sudo -E ./config.sh install
